services:
  nginx-ui:
    image: 'uozi/nginx-ui:latest'
    network_mode: host
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/opt/appdata/cache:/var/cache/nginx/cache'
        - '/opt/appdata/nginx-ui:/etc/nginx-ui'
        # Place the nginxui_lancache config files in this dir:
        - '/opt/appdata/nginx:/etc/nginx'
    environment:
        # Be sure to set your timezone
        - TZ=US/Eastern
    restart: always
    container_name: nginx-ui
    tty: true
    stdin_open: true
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Daily at 4 AM (cron format)
      - WATCHTOWER_CLEANUP=true  # Remove old images after updating
      - TZ=US/Eastern
